name: MLflow CI Skilled

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mlops:
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout@v4
        uses: actions/checkout@v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mlflow==3.11.1 pandas==2.3.3 scikit-learn==1.8.0 matplotlib dagshub cloudpickle numpy

      - name: Run MLflow Local Server
        run: |
          # Jalankan server lokal di background
          mlflow ui --port 5000 &
          sleep 15

      - name: Execute Modelling
        run: |
          cd MLProject
          python modelling.py

      - name: Get latest MLflow run_id and Download
        run: |
          RUN_ID=$(python -c "import mlflow; mlflow.set_tracking_uri('http://127.0.0.1:5000'); print(mlflow.search_runs(experiment_names=['Latihan_Model_Basic']).sort_values('start_time', ascending=False).iloc[0].run_id)")
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          
          # Download hasil ke folder outputs
          mlflow artifacts download --run-id $RUN_ID --dst-path ./outputs --tracking-uri http://127.0.0.1:5000

      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: MLflow-Results-Adinda
          path: ./outputs
          retention-days: 7

      - name: Complete job
        run: echo "Pipeline Finished"
