name: MLflow CI Skilled

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mlops:
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout@v4
        uses: actions/checkout@v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mlflow dagshub pandas scikit-learn matplotlib

      - name: Run MLflow Local Server
        run: |
          mlflow ui --port 5000 & 
          sleep 10 # Tunggu server nyala

      - name: Run mlflow project
        run: |
          cd MLProject
          mlflow run . --env-manager=local --experiment-name "Latihan_Model_Basic"

      - name: Get Artifacts from Local
        run: |
          # Karena servernya lokal, kita ambil folder mlruns yang terbentuk
          mkdir -p outputs
          cp -r mlruns/* outputs/
          
      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: MLflow-Results-Adinda
          path: outputs/
          retention-days: 7
