name: MLflow CI Skilled

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mlops:
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout@v4
        uses: actions/checkout@v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mlflow dagshub pandas scikit-learn matplotlib

      - name: Run MLflow Local Server
        run: |
          # Menjalankan server di background agar modelling.py bisa akses 127.0.0.1:5000
          mlflow ui --port 5000 &
          sleep 15

      - name: Run modelling.py
        run: |
          cd MLProject
          # Menjalankan file python secara langsung
          python modelling.py

      - name: Prepare Artifacts
        run: |
          # Mengambil hasil dari folder mlruns (lokal) ke folder outputs
          if [ -d "MLProject/mlruns" ]; then
            cp -r MLProject/mlruns/* outputs/
          else
            cp -r mlruns/* outputs/
          fi

      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: MLflow-Results-Adinda
          path: outputs/
          retention-days: 7

      - name: Complete job
        run: echo "Pipeline Finished"
